### ISSUE TITLE
想问一下怎么访问，启动后报404

### ISSUE THREAD

**Issue by luguo1331** [lorateam/Gotrip#2]

**Comment by geekhch** [comment]
404是资源不存在，检查下浏览器打开的url是不是正确吧

**Comment by luguo1331** [comment]
访问首页的url是什么啊？太旧没有写了



------------------ 原始邮件 ------------------
发件人: "三七"<notifications@github.com>; 
发送时间: 2019年10月31日(星期四) 晚上9:23
收件人: "lorateam/Gotrip"<Gotrip@noreply.github.com>; 
抄送: "大坏鸭子"<178205876@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [lorateam/Gotrip] 想问一下怎么访问，启动后报404 (#2)




404是资源不存在，检查下浏览器打开的url是不是正确吧
